<?php namespace App\Models;

class Rate extends Base
{
    protected $table = 'tarifas';
    protected $hidden = ['id'];
    protected $fillable = [];

    public static function fake()
    {
        return json_decode('[
            {
                "SEGMT_XLS" : ":porta.parti:porta.en_fi_post:porta.en_mo_post:sac.planes:bajas.parti.n1:bajas.parti.n2:kos.parti",
                "ACTIVO" : 0,
                "ID_TARIFA" : 97,
                "CODIGO" : "PTSEG",
                "TARIFA" : "(Legacy) Plan Contrato Clásico",
                "ID_OPERADOR" : 1,
                "SEGMENTO" : "Particular",
                "TIPO" : "VOZ",
                "CUOTA_LINEA_FIJO" : null,
                "LIMITES_A_FIJO" : null,
                "TARIFA_FUERA_FIJO" : null,
                "ESTABLECIMIENTO_FIJO" : null,
                "CUOTA_ADSL" : null,
                "CUOTA_LINEA_ADSL" : null,
                "CUOTA_TOTAL" : 12.3967,
                "BAJADA" : null,
                "SUBIDA" : null,
                "LLAMADAS_A_FIJO" : null,
                "LLAMADAS_A_MOVILES" : "0,26 cent\/min",
                "OTROS" : null,
                "MINUTOS" : null,
                "GCU" : null,
                "TARIFA_FUERA_MOVIL" : null,
                "ESTABLECIMIENTO_VOZ" : "20 cent",
                "SMS" : null,
                "LIMITES" : null,
                "DATOS" : null,
                "PERMANENCIA" : 18,
                "TIENE_PERMANENCIA" : "Si",
                "VPN" : " ",
                "FAMILIA" : "LEGACY_PAYG:NO_COMMITMENTS",
                "ESPECIAL" : null,
                "CUOTA_ESPECIAL12M" : 15.000006999999998,
                "TARIFA_OF_ESCRITO" : "Plan Contrato Clásico",
                "PORTABILIDADEMPRESA1" : null,
                "PORTABILIDADEMPRESA2" : null,
                "PORTABILIDADEMPRESA3" : null,
                "PORTABILIDADPARTICULAR1" : null,
                "PORTABILIDADPARTICULAR2" : null,
                "PORTABILIDADPARTICULAR3" : null,
                "ARGUMENT_PORT_E_1" : null,
                "ARGUMENT_PORT_E_2" : null,
                "ARGUMENT_PORT_E_3" : null,
                "ARGUMENT_PORT_P_1" : null,
                "ARGUMENT_PORT_P_2" : null,
                "ARGUMENT_PORT_P_3" : null,
                "PORTABILIDADPARTICULAR1_ONO" : null,
                "ARGUMENT_PORT_P_1_ONO" : null,
                "PORTABILIDADPARTICULAR2_ONO" : null,
                "ARGUMENT_PORT_P_2_ONO" : null,
                "PORTABILIDADPARTICULAR3_ONO" : null,
                "ARGUMENT_PORT_P_3_ONO" : null,
                "ORDEN" : null,
                "TIPO_TAR_COMP" : null,
                "ORIGEN_TAR" : null,
                "CUOTA_AVG" : null,
                "SALTO_LINEA" : null,
                "NOMBRE_COMERCIAL" : null,
                "MAS_LINEAS" : null,
                "SERVICIO_AGRUPADO" : null,
                "CON_TV" : null,
                "CUOTA_PROMO" : null,
                "DURACION" : null,
                "DTO_PROMO" : null,
                "TIPO_DTO_PROMO" : null,
                "FECHA" : null,
                "CODIGO_OFERTA" : null
            },
            {
                "SEGMT_XLS" : ":porta.parti:porta.en_fi_post:porta.en_mo_post:sac.planes:bajas.parti.n1:bajas.parti.n2:kos.parti",
                "ACTIVO" : 0,
                "ID_TARIFA" : 98,
                "CODIGO" : "SIXS2",
                "TARIFA" : "(Antigua) Plan Mini Clásica",
                "ID_OPERADOR" : 1,
                "SEGMENTO" : "Particular",
                "TIPO" : "VOZ",
                "CUOTA_LINEA_FIJO" : null,
                "LIMITES_A_FIJO" : null,
                "TARIFA_FUERA_FIJO" : null,
                "ESTABLECIMIENTO_FIJO" : null,
                "CUOTA_ADSL" : null,
                "CUOTA_LINEA_ADSL" : null,
                "CUOTA_TOTAL" : 14.876,
                "BAJADA" : null,
                "SUBIDA" : null,
                "LLAMADAS_A_FIJO" : null,
                "LLAMADAS_A_MOVILES" : null,
                "OTROS" : null,
                "MINUTOS" : null,
                "GCU" : null,
                "TARIFA_FUERA_MOVIL" : null,
                "ESTABLECIMIENTO_VOZ" : null,
                "SMS" : "12c\/sms (iva. Incl.)",
                "LIMITES" : null,
                "DATOS" : "1,5 GB",
                "PERMANENCIA" : 18,
                "TIENE_PERMANENCIA" : "Si",
                "VPN" : " ",
                "FAMILIA" : "ONO:NORMAL_BAJAS",
                "ESPECIAL" : null,
                "CUOTA_ESPECIAL12M" : 17.999959999999998,
                "TARIFA_OF_ESCRITO" : "Plan Mini Clásica",
                "PORTABILIDADEMPRESA1" : null,
                "PORTABILIDADEMPRESA2" : null,
                "PORTABILIDADEMPRESA3" : null,
                "PORTABILIDADPARTICULAR1" : null,
                "PORTABILIDADPARTICULAR2" : null,
                "PORTABILIDADPARTICULAR3" : null,
                "ARGUMENT_PORT_E_1" : null,
                "ARGUMENT_PORT_E_2" : null,
                "ARGUMENT_PORT_E_3" : null,
                "ARGUMENT_PORT_P_1" : null,
                "ARGUMENT_PORT_P_2" : null,
                "ARGUMENT_PORT_P_3" : null,
                "PORTABILIDADPARTICULAR1_ONO" : null,
                "ARGUMENT_PORT_P_1_ONO" : null,
                "PORTABILIDADPARTICULAR2_ONO" : null,
                "ARGUMENT_PORT_P_2_ONO" : null,
                "PORTABILIDADPARTICULAR3_ONO" : null,
                "ARGUMENT_PORT_P_3_ONO" : null,
                "ORDEN" : null,
                "TIPO_TAR_COMP" : null,
                "ORIGEN_TAR" : null,
                "CUOTA_AVG" : null,
                "SALTO_LINEA" : null,
                "NOMBRE_COMERCIAL" : null,
                "MAS_LINEAS" : null,
                "SERVICIO_AGRUPADO" : null,
                "CON_TV" : null,
                "CUOTA_PROMO" : null,
                "DURACION" : null,
                "DTO_PROMO" : null,
                "TIPO_DTO_PROMO" : null,
                "FECHA" : null,
                "CODIGO_OFERTA" : null
            },
            {
                "SEGMT_XLS" : ":porta.parti:porta.en_fi_post:porta.en_mo_post:sac.planes:bajas.parti.n1:bajas.parti.n2:kos.parti",
                "ACTIVO" : 0,
                "ID_TARIFA" : 99,
                "CODIGO" : "SUPER",
                "TARIFA" : "(Legacy) Plan Super 90x1",
                "ID_OPERADOR" : 1,
                "SEGMENTO" : "Particular",
                "TIPO" : "VOZ",
                "CUOTA_LINEA_FIJO" : null,
                "LIMITES_A_FIJO" : null,
                "TARIFA_FUERA_FIJO" : null,
                "ESTABLECIMIENTO_FIJO" : null,
                "CUOTA_ADSL" : null,
                "CUOTA_LINEA_ADSL" : null,
                "CUOTA_TOTAL" : 12,
                "BAJADA" : null,
                "SUBIDA" : null,
                "LLAMADAS_A_FIJO" : null,
                "LLAMADAS_A_MOVILES" : null,
                "OTROS" : null,
                "MINUTOS" : null,
                "GCU" : null,
                "TARIFA_FUERA_MOVIL" : null,
                "ESTABLECIMIENTO_VOZ" : null,
                "SMS" : null,
                "LIMITES" : null,
                "DATOS" : null,
                "PERMANENCIA" : 18,
                "TIENE_PERMANENCIA" : "Si",
                "VPN" : " ",
                "FAMILIA" : "LEGACY_PAYG",
                "ESPECIAL" : null,
                "CUOTA_ESPECIAL12M" : 14.52,
                "TARIFA_OF_ESCRITO" : "Plan Super 90x1",
                "PORTABILIDADEMPRESA1" : null,
                "PORTABILIDADEMPRESA2" : null,
                "PORTABILIDADEMPRESA3" : null,
                "PORTABILIDADPARTICULAR1" : null,
                "PORTABILIDADPARTICULAR2" : null,
                "PORTABILIDADPARTICULAR3" : null,
                "ARGUMENT_PORT_E_1" : null,
                "ARGUMENT_PORT_E_2" : null,
                "ARGUMENT_PORT_E_3" : null,
                "ARGUMENT_PORT_P_1" : null,
                "ARGUMENT_PORT_P_2" : null,
                "ARGUMENT_PORT_P_3" : null,
                "PORTABILIDADPARTICULAR1_ONO" : null,
                "ARGUMENT_PORT_P_1_ONO" : null,
                "PORTABILIDADPARTICULAR2_ONO" : null,
                "ARGUMENT_PORT_P_2_ONO" : null,
                "PORTABILIDADPARTICULAR3_ONO" : null,
                "ARGUMENT_PORT_P_3_ONO" : null,
                "ORDEN" : null,
                "TIPO_TAR_COMP" : null,
                "ORIGEN_TAR" : null,
                "CUOTA_AVG" : null,
                "SALTO_LINEA" : null,
                "NOMBRE_COMERCIAL" : null,
                "MAS_LINEAS" : null,
                "SERVICIO_AGRUPADO" : null,
                "CON_TV" : null,
                "CUOTA_PROMO" : null,
                "DURACION" : null,
                "DTO_PROMO" : null,
                "TIPO_DTO_PROMO" : null,
                "FECHA" : null,
                "CODIGO_OFERTA" : null
            },
            {
                "SEGMT_XLS" : ":porta.parti:porta.en_fi_post:porta.en_mo_post:sac.planes:bajas.parti.n1:bajas.parti.n2:kos.parti",
                "ACTIVO" : 0,
                "ID_TARIFA" : 100,
                "CODIGO" : "SYUCL",
                "TARIFA" : "(Antigua) Superyuser Clásica",
                "ID_OPERADOR" : 1,
                "SEGMENTO" : "Particular",
                "TIPO" : "VOZ",
                "CUOTA_LINEA_FIJO" : null,
                "LIMITES_A_FIJO" : null,
                "TARIFA_FUERA_FIJO" : null,
                "ESTABLECIMIENTO_FIJO" : null,
                "CUOTA_ADSL" : null,
                "CUOTA_LINEA_ADSL" : null,
                "CUOTA_TOTAL" : 17.355,
                "BAJADA" : null,
                "SUBIDA" : null,
                "LLAMADAS_A_FIJO" : null,
                "LLAMADAS_A_MOVILES" : null,
                "OTROS" : null,
                "MINUTOS" : null,
                "GCU" : null,
                "TARIFA_FUERA_MOVIL" : null,
                "ESTABLECIMIENTO_VOZ" : null,
                "SMS" : null,
                "LIMITES" : null,
                "DATOS" : "1,5Gb",
                "PERMANENCIA" : 18,
                "TIENE_PERMANENCIA" : "Si",
                "VPN" : " ",
                "FAMILIA" : "NORMAL_BAJAS",
                "ESPECIAL" : null,
                "CUOTA_ESPECIAL12M" : 20.99955,
                "TARIFA_OF_ESCRITO" : "Superyuser Clásica",
                "PORTABILIDADEMPRESA1" : null,
                "PORTABILIDADEMPRESA2" : null,
                "PORTABILIDADEMPRESA3" : null,
                "PORTABILIDADPARTICULAR1" : null,
                "PORTABILIDADPARTICULAR2" : null,
                "PORTABILIDADPARTICULAR3" : null,
                "ARGUMENT_PORT_E_1" : null,
                "ARGUMENT_PORT_E_2" : null,
                "ARGUMENT_PORT_E_3" : null,
                "ARGUMENT_PORT_P_1" : null,
                "ARGUMENT_PORT_P_2" : null,
                "ARGUMENT_PORT_P_3" : null,
                "PORTABILIDADPARTICULAR1_ONO" : null,
                "ARGUMENT_PORT_P_1_ONO" : null,
                "PORTABILIDADPARTICULAR2_ONO" : null,
                "ARGUMENT_PORT_P_2_ONO" : null,
                "PORTABILIDADPARTICULAR3_ONO" : null,
                "ARGUMENT_PORT_P_3_ONO" : null,
                "ORDEN" : null,
                "TIPO_TAR_COMP" : null,
                "ORIGEN_TAR" : null,
                "CUOTA_AVG" : null,
                "SALTO_LINEA" : null,
                "NOMBRE_COMERCIAL" : null,
                "MAS_LINEAS" : null,
                "SERVICIO_AGRUPADO" : null,
                "CON_TV" : null,
                "CUOTA_PROMO" : null,
                "DURACION" : null,
                "DTO_PROMO" : null,
                "TIPO_DTO_PROMO" : null,
                "FECHA" : null,
                "CODIGO_OFERTA" : null
            }
        ]');
    }
}